analyzer:
  plugins:
    - dart_code_metrics

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    - always_declare_return_types
    - avoid_unused_constructor_parameters
    - directives_ordering
    - omit_local_variable_types
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - sized_box_for_whitespace
    - sort_child_properties_last
    - sort_pub_dependencies
    - type_annotate_public_apis
    - unawaited_futures
    - use_named_constants
    - use_super_parameters

dart_code_metrics:
  rules-exclude:
    - lib/firebase_options.dart
  rules:
    - always-remove-listener
    - avoid-unused-parameters
    - format-comment
    - member-ordering:
        alphabetize: false
        order:
          - constructors
          - public-fields
          - public-getters
          - public-setters
          - private-fields
          - private-getters
          - private-setters
          - public-methods
          - private-methods
    - no-boolean-literal-compare
    - prefer-trailing-comma
