name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  faker: ^2.1.0
  file_picker: ^8.0.0+1
  file_saver: ^0.2.12
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.12
  flutter_login: ^5.0.0
  flutter_supabase_chat_core:
    path: ../
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  image_picker: ^1.0.7
  mime: ^1.0.5
  open_filex: ^4.4.0
  path_provider: ^2.1.2
  supabase_flutter: ^2.3.4
  timeago: ^3.6.1
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/