name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  faker: ^2.2.0
  file_picker: ^8.1.3
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  flutter_login: ^5.0.0
  flutter_supabase_chat_core:
    path: ../
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  image_picker: ^1.1.2
  mime: ^1.0.5
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  supabase_flutter: ^2.8.0
  timeago: ^3.7.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/