name: flutter_supabase_chat_core
description: >
  Actively maintained, community-driven Supabase BaaS for chat applications
  with an optional chat UI.
version: 1.0.0
homepage: https://flutter-supabase-chat-core.insideapp.it
repository: https://github.com/insideapp-srl/flutter_supabase_chat_core

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  meta: ^1.11.0
  supabase_flutter: ^2.4.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter